### ISSUE TITLE
ymp env update doesn't update pip packages

### ISSUE THREAD

**Issue by shafferm** [epruesse/ymp#14]
I needed to update my SCNIC package to fix a bug. I called `ymp env update` to update my package to the newest version available in pip but it was not updated. I tried going into the conda environment used by that rule and update from in there. Calling `pip install -U SCNIC` also installed a newer version of numpy from pip which superseded the installed conda version. Removing this caused numpy to not be found so I had to reinstall numpy via conda for it to be found again.

To avoid the problem again my workaround was to specify a version of SCNIC in the SCNIC.yml file and update as I uploaded new fixed versions to pypi which forced the environment to be rebuilt.

**Comment by shafferm** [comment]
A nice feature related to this would be to have `ymp env remove {name}` to delete an environment.

**Comment by epruesse** [comment]
`ymp env update` runs `conda env update`. I guess that doesn't try to update pip then?

We could have our own conda channel for the unpublished tools. Or we could build something that installs/updates pip/github dependencies manually.

`ymp env remove` would be easy enough. Currently, `ymp env clean` removes all envs for which no `yml` exists. Would `ymp env clean ENVNAME` work? Or is that too confusing?

I'm also thinking to replace `ymp env update` and `ymp env create` with `ymp env install`. The latter could have an `--force` to force re-install. The current `update` already runs `create` to make sure the env is there, so having `create` is sort of redundant, but `update` makes little sense for install-and-update.

**Comment by shafferm** [comment]
> We could have our own conda channel for the unpublished tools. Or we could build something that installs/updates pip/github dependencies manually.

I think the fix you suggested by making `ymp env install` would be best. It would be nice to have something that would update pip/github itself but I don't think that would be worth the time investment when reinstalling an environment doesn't take too long.

> ymp env remove would be easy enough. Currently, ymp env clean removes all envs for which no yml exists. Would ymp env clean ENVNAME work? Or is that too confusing?

I think `ymp env clean ENVNAME` is perfectly fine; I actually tried that to see if it would work on my own before posting this. I'd also suggest possibly having a `ymp env clean --all` to just clean all environments, but I'd hope no one would ever have to use it.

**Comment by epruesse** [comment]
Is this still an issue?

**Comment by epruesse** [comment]
Having `pip:` dependencies in the env breaks reproducibility - conda won't archive those.
