### ISSUE TITLE
Make ymp environments findable by local rules

### ISSUE THREAD

**Issue by shafferm** [epruesse/ymp#21]
YMP currently requires rules to sit alongside their associated environment file (`srcdir("environment.yml")`). Environments that are packaged with YMP should be findable by local rules so that environments don't need to be duplicated for use with user generated rule files.

Also I would vote for environments being in their own directory to go along with this change. I feel like the mixture of .rules and .yml files in the rules directory is kind of confusing at first and really clutters the rules directory. By splitting and having a dedicated environments directory that could make fixing the local rules issue easier. Although it would then require something for local environments to work I'd guess.

**Comment by epruesse** [comment]
YMP will now look for the environment files next to each Snakefile on the include stack and in the folder `conda_envs` next to the folder containing the Snakefile. The those paths can be configured via `search_paths: conda_env:` (see defaults.yml).
