### ISSUE TITLE
ymp env activate bug

### ISSUE THREAD

**Issue by shafferm** [epruesse/ymp#42]
I can run `ymp env activate --help` and it runs appropriately but when I try to run `ymp env activate dada2_qiime1` I get an error which I have pasted below. This is present in the list of installed environments. I don't know if I'm missing some configuration or what. YMP was pulled and installed just before this was ran.

> Traceback (most recent call last):
>   File "/Users/mish0397/miniconda3/envs/ymp/bin/ymp", line 10, in <module>
>     sys.exit(main())
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/mish0397/miniconda3/envs/ymp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/mish0397/git_sw/ymp/ymp/cli/env.py", line 156, in activate
>     if envname not in ymp.env.by_name:
> AttributeError: module 'ymp' has no attribute 'env'

**Comment by epruesse** [comment]
Should be fixed now
